/*
 * Copyright (c) 2024 Cadence Design Systems, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Compile-time Xtensa LX configuration sanity checks.
 *
 * These checks enforce the hardware prerequisites documented in README.md.
 * All checks use macros from <xtensa/config/core-isa.h>, which is generated
 * by the Xtensa toolchain for the selected XTENSA_CORE.  A build failure here
 * means the chosen core configuration does not meet Zephyr's requirements;
 * see the error message and README.md for remediation steps.
 *
 * Checks performed (in order):
 *
 *  [1] XCHAL_NUM_INTLEVELS >= 2
 *      Zephyr requires at least two distinct interrupt levels.
 *      See https://github.com/zephyrproject-rtos/zephyr/issues/84453
 *
 *  [2] At least one TIMER interrupt at level <= XCHAL_EXCM_LEVEL
 *      Zephyr's system timer driver needs a timer interrupt that can fire
 *      while the kernel masks interrupts up to EXCM_LEVEL.
 *      Checks all 32-bit interrupt groups (up to 128 interrupts total).
 *
 *  [3] At least one SOFTWARE interrupt at level <= XCHAL_EXCM_LEVEL
 *      Zephyr uses a SW interrupt for its internal yield/reschedule path;
 *      it must be reachable under normal critical-section masking.
 *      Checks all 32-bit interrupt groups (up to 128 interrupts total).
 *
 *  [4] WARNING: SW interrupt(s) exist above XCHAL_EXCM_LEVEL   (non-fatal)
 *      If any SW interrupt is above EXCM_LEVEL, Zephyr may select it for
 *      internal use but then only masks up to EXCM_LEVEL, leaving it
 *      unguarded.  Modify the core config or apply the upstream patch.
 *      Checks all 32-bit interrupt groups (up to 128 interrupts total).
 *      See https://github.com/zephyrproject-rtos/zephyr/pull/87483
 *
 *  [5] CONFIG_SMP requires XCHAL_SUBSYS_IPI_S0C0_INTNUM (multi-core IPI)
 *      Single-core configs do not have inter-processor interrupts and cannot
 *      support SMP.
 *
 *  [6] IPI set-0 interrupt must be at level <= XCHAL_EXCM_LEVEL  (SMP only)
 *      The scheduler IPI must be maskable under normal critical sections.
 *      Uses XCHAL_INT<n>_LEVEL (not a 32-bit bitmask shift) because the
 *      interrupt number may be >= 32 (up to 128 in some subsystem configs).
 *
 *  [7] IPI set-0 interrupt must be edge-triggered  (SMP only)
 *      Edge triggering ensures each IPI is a single self-clearing pulse.
 *      A level-triggered IPI would re-assert continuously until cleared.
 *      Uses XCHAL_INT<n>_TYPE (not a 32-bit bitmask shift) for the same
 *      reason as check [6].
 */

#include <xtensa/config/core-isa.h>

/* =========================================================================
 * Helpers: resolve XCHAL_INTLEVELn_ANDBELOW_MASKm for n = XCHAL_EXCM_LEVEL,
 * across all 32-bit interrupt groups m = 0..3 (covering up to 128 interrupts).
 *
 * XCHAL_INTLEVELn_ANDBELOW_MASKm has bit k set when interrupt (32*m + k) has
 * level <= n.  Group 0 (no numeric suffix) covers interrupts 0-31; groups 1-3
 * (suffix 1/2/3) cover interrupts 32-63, 64-95, and 96-127 respectively, and
 * are only defined by the toolchain when XCHAL_NUM_INTERRUPTS exceeds the
 * group boundary.
 *
 * The double-indirection (_PASTE3 → _PASTE3_INNER) is the standard C
 * preprocessor idiom that forces expansion of macro arguments before pasting:
 *  - _PASTE3(a, b, c) passes b (= XCHAL_EXCM_LEVEL) to _PASTE3_INNER
 *    as an ordinary argument, so the preprocessor expands it to its value
 *    (e.g. 3) before _PASTE3_INNER's ## operator concatenates the tokens.
 *  - Result: XCHAL_INTLEVEL3_ANDBELOW_MASK  (for XCHAL_EXCM_LEVEL == 3)
 * ========================================================================= */
#define _XCHAL_PASTE3_INNER(a, b, c)  a##b##c
#define _XCHAL_PASTE3(a, b, c)        _XCHAL_PASTE3_INNER(a, b, c)

/* Group 0: interrupts 0-31 (always present). */
#define _XCHAL_EXCM_ANDBELOW_MASK \
	_XCHAL_PASTE3(XCHAL_INTLEVEL, XCHAL_EXCM_LEVEL, _ANDBELOW_MASK)

/*
 * Groups 1-3: XCHAL_INTLEVELn_ANDBELOW_MASK{1,2,3} are only generated by
 * the Xtensa toolchain when XCHAL_NUM_INTERRUPTS exceeds the group boundary
 * (> 32, > 64, > 96 respectively).  Use the token-pasted name when the
 * group is present; fall back to 0 (no interrupts in that group) otherwise.
 */
#if XCHAL_NUM_INTERRUPTS > 32
#define _XCHAL_EXCM_ANDBELOW_MASK_1 \
	_XCHAL_PASTE3(XCHAL_INTLEVEL, XCHAL_EXCM_LEVEL, _ANDBELOW_MASK1)
#else
#define _XCHAL_EXCM_ANDBELOW_MASK_1  0
#endif
#if XCHAL_NUM_INTERRUPTS > 64
#define _XCHAL_EXCM_ANDBELOW_MASK_2 \
	_XCHAL_PASTE3(XCHAL_INTLEVEL, XCHAL_EXCM_LEVEL, _ANDBELOW_MASK2)
#else
#define _XCHAL_EXCM_ANDBELOW_MASK_2  0
#endif
#if XCHAL_NUM_INTERRUPTS > 96
#define _XCHAL_EXCM_ANDBELOW_MASK_3 \
	_XCHAL_PASTE3(XCHAL_INTLEVEL, XCHAL_EXCM_LEVEL, _ANDBELOW_MASK3)
#else
#define _XCHAL_EXCM_ANDBELOW_MASK_3  0
#endif

/*
 * XCHAL_INTTYPE_MASK{1,2,3}_{TIMER,SOFTWARE} are generated by the Xtensa
 * toolchain only when XCHAL_NUM_INTERRUPTS exceeds the respective group
 * boundary (> 32, > 64, > 96).  Provide #ifndef fallbacks of 0 so the
 * combined expressions below compile unconditionally for all configs,
 * including small cores such as hifi5s_ao_7 (22 interrupts) where these
 * macros are absent from core-isa.h entirely.
 */
#ifndef XCHAL_INTTYPE_MASK1_TIMER
#define XCHAL_INTTYPE_MASK1_TIMER  0
#endif
#ifndef XCHAL_INTTYPE_MASK2_TIMER
#define XCHAL_INTTYPE_MASK2_TIMER  0
#endif
#ifndef XCHAL_INTTYPE_MASK3_TIMER
#define XCHAL_INTTYPE_MASK3_TIMER  0
#endif
#ifndef XCHAL_INTTYPE_MASK1_SOFTWARE
#define XCHAL_INTTYPE_MASK1_SOFTWARE  0
#endif
#ifndef XCHAL_INTTYPE_MASK2_SOFTWARE
#define XCHAL_INTTYPE_MASK2_SOFTWARE  0
#endif
#ifndef XCHAL_INTTYPE_MASK3_SOFTWARE
#define XCHAL_INTTYPE_MASK3_SOFTWARE  0
#endif

/*
 * Combined interrupt-presence tests across all four 32-bit groups.
 *
 * _XCHAL_TIMER_IN_EXCM  - non-zero if ANY timer interrupt has level <= EXCM.
 * _XCHAL_SW_IN_EXCM     - non-zero if ANY SW interrupt has level <= EXCM.
 * _XCHAL_SW_ABOVE_EXCM  - non-zero if ANY SW interrupt has level >  EXCM.
 *
 * For configs with fewer than 128 interrupts the higher-group masks are all
 * 0 (via the fallbacks and _XCHAL_EXCM_ANDBELOW_MASK_N = 0 guards above),
 * so their OR contribution is always 0 -- no #if cascade is needed.
 *
 * NOTE on _XCHAL_SW_ABOVE_EXCM: when _XCHAL_EXCM_ANDBELOW_MASK_N == 0,
 * ~0 = 0xFFFFFFFF, but the corresponding XCHAL_INTTYPE_MASK{N}_SOFTWARE
 * fallback is also 0, so the AND is 0 -- no false positives.
 */
#define _XCHAL_TIMER_IN_EXCM \
	((XCHAL_INTTYPE_MASK_TIMER  & _XCHAL_EXCM_ANDBELOW_MASK)   | \
	 (XCHAL_INTTYPE_MASK1_TIMER & _XCHAL_EXCM_ANDBELOW_MASK_1) | \
	 (XCHAL_INTTYPE_MASK2_TIMER & _XCHAL_EXCM_ANDBELOW_MASK_2) | \
	 (XCHAL_INTTYPE_MASK3_TIMER & _XCHAL_EXCM_ANDBELOW_MASK_3))
#define _XCHAL_SW_IN_EXCM \
	((XCHAL_INTTYPE_MASK_SOFTWARE  & _XCHAL_EXCM_ANDBELOW_MASK)   | \
	 (XCHAL_INTTYPE_MASK1_SOFTWARE & _XCHAL_EXCM_ANDBELOW_MASK_1) | \
	 (XCHAL_INTTYPE_MASK2_SOFTWARE & _XCHAL_EXCM_ANDBELOW_MASK_2) | \
	 (XCHAL_INTTYPE_MASK3_SOFTWARE & _XCHAL_EXCM_ANDBELOW_MASK_3))
#define _XCHAL_SW_ABOVE_EXCM \
	((XCHAL_INTTYPE_MASK_SOFTWARE  & ~_XCHAL_EXCM_ANDBELOW_MASK)   | \
	 (XCHAL_INTTYPE_MASK1_SOFTWARE & ~_XCHAL_EXCM_ANDBELOW_MASK_1) | \
	 (XCHAL_INTTYPE_MASK2_SOFTWARE & ~_XCHAL_EXCM_ANDBELOW_MASK_2) | \
	 (XCHAL_INTTYPE_MASK3_SOFTWARE & ~_XCHAL_EXCM_ANDBELOW_MASK_3))

/* =========================================================================
 * Check [1]: At least 2 interrupt levels.
 *
 * XCHAL_NUM_INTLEVELS counts non-NMI interrupt levels in the core.
 * Zephyr's interrupt model separates "maskable" (level <= EXCM_LEVEL) from
 * "critical" (level > EXCM_LEVEL) interrupts; this distinction is only
 * meaningful when there are at least two levels.
 *
 * See https://github.com/zephyrproject-rtos/zephyr/issues/84453
 * ========================================================================= */
#if XCHAL_NUM_INTLEVELS < 2
#error "Xtensa core has fewer than 2 interrupt levels (XCHAL_NUM_INTLEVELS < 2)." \
       " Zephyr requires at least 2 interrupt levels." \
       " See https://github.com/zephyrproject-rtos/zephyr/issues/84453"
#endif

/* =========================================================================
 * Check [2]: At least one TIMER interrupt at level <= XCHAL_EXCM_LEVEL.
 *
 * _XCHAL_TIMER_IN_EXCM ORs the (INTTYPE_MASK_TIMER & ANDBELOW_MASK)
 * intersection across all 32-bit interrupt groups present in the config.
 * The result must be non-zero (at least one such timer exists).
 *
 * Example (hifi5s_ao_7, EXCM_LEVEL=3, XCHAL_NUM_INTERRUPTS=22 <= 32):
 *   XCHAL_INTTYPE_MASK_TIMER        = 0x00002440  (INT6, INT10, INT13)
 *   XCHAL_INTLEVEL3_ANDBELOW_MASK   = 0x003F8FFF
 *   _XCHAL_TIMER_IN_EXCM            = 0x00002440  -> non-zero, check passes
 * ========================================================================= */
#if _XCHAL_TIMER_IN_EXCM == 0
#error "No timer interrupt is configured at level <= XCHAL_EXCM_LEVEL." \
       " Zephyr's system timer requires at least one timer interrupt" \
       " at or below EXCM_LEVEL."
#endif

/* =========================================================================
 * Check [3]: At least one SOFTWARE interrupt at level <= XCHAL_EXCM_LEVEL.
 *
 * _XCHAL_SW_IN_EXCM ORs the (INTTYPE_MASK_SOFTWARE & ANDBELOW_MASK)
 * intersection across all 32-bit interrupt groups present in the config.
 * The result must be non-zero (at least one such SW interrupt exists).
 *
 * Example (hifi5s_ao_7, EXCM_LEVEL=3, XCHAL_NUM_INTERRUPTS=22 <= 32):
 *   XCHAL_INTTYPE_MASK_SOFTWARE     = 0x00000880  (INT7 @ L1, INT11 @ L3)
 *   XCHAL_INTLEVEL3_ANDBELOW_MASK   = 0x003F8FFF
 *   _XCHAL_SW_IN_EXCM               = 0x00000880  -> non-zero, check passes
 * ========================================================================= */
#if _XCHAL_SW_IN_EXCM == 0
#error "No software interrupt is configured at level <= XCHAL_EXCM_LEVEL." \
       " Zephyr requires at least one SW interrupt at or below EXCM_LEVEL."
#endif

/* =========================================================================
 * Check [4]: WARNING — SW interrupt(s) above XCHAL_EXCM_LEVEL.
 *
 * _XCHAL_SW_ABOVE_EXCM ORs the (INTTYPE_MASK_SOFTWARE & ~ANDBELOW_MASK)
 * complement across all 32-bit interrupt groups present in the config.
 * If non-zero, at least one SW interrupt has level > EXCM_LEVEL.
 *
 * Zephyr may select such an interrupt for internal use but only masks
 * up to EXCM_LEVEL during critical processing, leaving the high-level SW
 * interrupt unguarded.  This produces subtle incorrect behaviour.
 *
 * This is a #warning, not a #error, because an upstream patch may already
 * be applied locally.
 *
 * Resolution:
 *   - Reconfigure the core so that all SW interrupts are at level
 *     <= XCHAL_EXCM_LEVEL, OR
 *   - Apply the patch at https://github.com/zephyrproject-rtos/zephyr/pull/87483
 * ========================================================================= */
#if _XCHAL_SW_ABOVE_EXCM != 0
#warning "One or more SW interrupts are at level > XCHAL_EXCM_LEVEL." \
         " Zephyr may select such an interrupt for internal use but only" \
         " masks up to EXCM_LEVEL, leaving it unguarded." \
         " Modify the core config or apply:" \
         " https://github.com/zephyrproject-rtos/zephyr/pull/87483"
#endif

/* =========================================================================
 * Checks [5-7] apply only to SMP (multi-core) builds.
 * ========================================================================= */
#if defined(CONFIG_SMP)

/* -------------------------------------------------------------------------
 * Check [5]: Multi-core IPI support must be present.
 *
 * XCHAL_SUBSYS_IPI_S0C0_INTNUM is defined only for multi-core subsystem
 * configurations; single-core configs omit it entirely.  Without IPI,
 * one core cannot signal another and SMP cannot function.
 * ------------------------------------------------------------------------- */
#ifndef XCHAL_SUBSYS_IPI_S0C0_INTNUM
#error "CONFIG_SMP=y requires a multi-core config with IPI support" \
       " (XCHAL_SUBSYS_IPI_S0C0_INTNUM is not defined)." \
       " Use a multi-core XTENSA_CORE or disable CONFIG_SMP."
#endif

/* -------------------------------------------------------------------------
 * Check [6]: IPI set-0 interrupt must be at level <= XCHAL_EXCM_LEVEL.
 *
 * The first IPI set (set 0) is the one Zephyr's scheduler uses.  It must
 * be maskable under normal critical sections (i.e. at level <= EXCM_LEVEL)
 * so that scheduler IPIs are properly deferred when the kernel holds locks.
 *
 * NOTE: The interrupt number can be >= 32 (Xtensa subsystem configs support
 * up to 128 interrupts), so (1u << XCHAL_SUBSYS_IPI_S0C0_INTNUM) would
 * produce undefined behaviour and a 32-bit ANDBELOW_MASK would not cover
 * the bit.  Instead, we use the per-interrupt XCHAL_INT<n>_LEVEL macro
 * via token-pasting to read the interrupt level directly.
 *
 * Example (hifi5s_4c_l2, EXCM_LEVEL=1, IPI=24):
 *   XCHAL_INT24_LEVEL  = 1
 *   XCHAL_EXCM_LEVEL   = 1
 *   1 <= 1             -> check passes
 * ------------------------------------------------------------------------- */

/* Expands to XCHAL_INT<n>_LEVEL for n = XCHAL_SUBSYS_IPI_S0C0_INTNUM. */
#define _XCHAL_IPI_S0C0_INTLEVEL \
	_XCHAL_PASTE3(XCHAL_INT, XCHAL_SUBSYS_IPI_S0C0_INTNUM, _LEVEL)

#if _XCHAL_IPI_S0C0_INTLEVEL > XCHAL_EXCM_LEVEL
#error "IPI set-0 interrupt (XCHAL_SUBSYS_IPI_S0C0_INTNUM) is above" \
       " XCHAL_EXCM_LEVEL.  The first IPI set must be at level <=" \
       " EXCM_LEVEL for correct SMP scheduler operation."
#endif

/* -------------------------------------------------------------------------
 * Check [7]: IPI set-0 interrupt must be edge-triggered.
 *
 * IPI interrupts must be edge-triggered: each xthal_ipi_trigger() call
 * generates a single pulse that self-clears.  A level-triggered IPI would
 * continuously re-assert until explicitly cleared, causing the handler to
 * re-enter indefinitely.
 *
 * NOTE: The interrupt number can be >= 32 (Xtensa subsystem configs support
 * up to 128 interrupts), so (1u << XCHAL_SUBSYS_IPI_S0C0_INTNUM) would
 * produce undefined behaviour and a 32-bit XCHAL_INTTYPE_MASK_EXTERN_EDGE
 * would not cover the bit.  Instead, we use the per-interrupt
 * XCHAL_INT<n>_TYPE macro via token-pasting and compare it directly to
 * XTHAL_INTTYPE_EXTERN_EDGE (= 1, a stable Xtensa ABI constant).
 *
 * Example (hifi5s_4c_l2, IPI=24):
 *   XCHAL_INT24_TYPE  = XTHAL_INTTYPE_EXTERN_EDGE (1)  -> check passes
 * ------------------------------------------------------------------------- */

/* XTHAL_INTTYPE_EXTERN_EDGE is defined in <xtensa/hal.h>; its value is 1
 * per the Xtensa architecture ABI.  Provide a fallback so we do not need
 * to pull in the full HAL header just for this constant. */
#ifndef XTHAL_INTTYPE_EXTERN_EDGE
#define XTHAL_INTTYPE_EXTERN_EDGE  1
#endif

/* Expands to XCHAL_INT<n>_TYPE for n = XCHAL_SUBSYS_IPI_S0C0_INTNUM. */
#define _XCHAL_IPI_S0C0_INTTYPE \
	_XCHAL_PASTE3(XCHAL_INT, XCHAL_SUBSYS_IPI_S0C0_INTNUM, _TYPE)

#if _XCHAL_IPI_S0C0_INTTYPE != XTHAL_INTTYPE_EXTERN_EDGE
#error "IPI set-0 interrupt (XCHAL_SUBSYS_IPI_S0C0_INTNUM) is not" \
       " edge-triggered (XCHAL_INT<n>_TYPE != XTHAL_INTTYPE_EXTERN_EDGE)." \
       " IPI interrupts must be configured as edge-triggered" \
       " (XTHAL_INTTYPE_EXTERN_EDGE) in the Xtensa subsystem."
#endif

#endif /* CONFIG_SMP */
